source 'https://rubygems.org'

ruby '>= 3.0', '< 3.5'
# after pushing this fuzzy match thru chef, commit to make this be:
# ruby '3.3.4'

gem 'berkshelf', '>= 8.0.15'
gem 'chef', '17.7.22'
gem 'chefspec', '>= 9.3.6'
gem 'kitchen-inspec', '>= 2.6.2'

gem 'test-kitchen', '>= 3.5.0'

gem 'kitchen-docker', '>= 2.14.0'
gem 'kitchen-dokken', '>= 2.17.4'

gem 'kitchen-ec2', '>= 3.14.0'

# Provides `sftp` transport to test-kitchen for faster cookbook upload.
gem 'kitchen-sync'

gem 'json', '>= 2.3.0' # 2.3.0 resolved some Ruby 2.7 deprecation warnings

gem 'racc' # test-kitchen 3.4.0 has an undeclared dependency on racc that breaks on Ruby 3.3.4. If we upgrade test-kitchen, we can drop this line.
