module AiSystemPrompts::EvaluateSystemPromptHelper
  def self.get_system_prompt(level, unit, evaluation_type)
    evaluation_criteria = get_evaluation_criteria(level)
    single_student_evaluation_structure = <<~TEXT
      Please review the student's work. Respond in correctly formatted JSON.
      evaluationCriteria should just be a copy of #{evaluation_criteria}.
      aiEvaluation should be your overall assessment of the student's work. Respond with "great", "ok", or "needs revision".
      aiReasoning should be one sentence with your reasoning.
      specificEvaluations should be an array of objects with the following structure: {evaluationCriteria: "specific evaluation criteria", aiEvaluation: Respond with "great", "ok", "needs revision" or "not attempted", aiReasoning: "reasoning for specific evaluation"}. generated by iterating through the evaluationCriteria.
    TEXT
    section_summary_evaluation_structure = <<~TEXT
      Please review the evaluations of the student responses. Respond in correctly formatted JSON.
      evaluationCriteria should just be a copy of "Summarize".
      aiEvaluation should be your assessment of the class's overall work. Respond with "review the concept" or "move on to the next lesson".
      aiReasoning should be one sentence with your reasoning including the names of any students who need more help.`;
    TEXT
    evaluation_structure = evaluation_type == SharedConstants::AI_EVALUATION_TYPES[:SINGLE_STUDENT] ? single_student_evaluation_structure : section_summary_evaluation_structure
    prompt = AiSystemPrompts::SystemPromptHelper.get_basic_system_prompt(level, unit)
    prompt << evaluation_structure
  end

  # TODO: As we develop the Learning Trajectory and the specifics of how each task should be evaluated,
  # we should update this method. Right now we're just defaulting to assessing against the level's instructions
  # or very generic criteria for programming levels.
  def self.get_evaluation_criteria(level)
    skills_based_evaluation_criteria = {
      # Lesson 3, Level 2
      22595 => {
        level_type: "Programming",
        programming_task_type: "Modify existing code",
        programming_concept_skills: [
          {
            skill: "Declare variables correctly",
            evaluation_criteria: "Did the students declare all of the variables in their code correctly?",
            concept: "Variables"
          },
          {
            skill: "Name variables according to conventions",
            evaluation_criteria: "Are there any spaces in variable names? Are there any misspelled variable names? Do variable names follow casing conventions?",
            concept: "Variables"
          },
        ],
        computational_thinking_skills: [
          {
            skill: "Identify errors in starter code",
            evaluation_criteria: "Does the code compile without errors?",
            concept: "Debugging"
          },
          {
            skill: "Fix errors in starter code",
            evaluation_criteria: "Does the code compile without errors?",
            concept: "Debugging",
          },
        ],
        habits_of_work: [
          {
            skill: "Share work with partner verbally",
            concept: "Communication"
          },
        ],
      },
      # Lesson 3, Level 6
      22630 => {
        level_type: "Programming",
        programming_task_type: "Write new code with guidance",
        programming_concept_skills: [
          {
            skill: "Increment values stored in variables",
            evaluation_criteria: "Does the student's added code increment the values stored in the variables correctly?",
            concept: "Variables"
          },
        ],
        computational_thinking_skills: [
          {
            skill: "Pattern matching",
            evaluation_criteria: "Does the student's added code match the pattern of the existing code?",
            concept: "Pattern recognition"
          },
        ],
      },
    }
    levels_with_skills_based_criteria = skills_based_evaluation_criteria.keys
    if levels_with_skills_based_criteria.include?(level.id)
      evaluation_criteria = []
      skills_based_evaluation_criteria[level.id][:programming_concept_skills].each do |criterion|
        evaluation_criteria << criterion[:evaluation_criteria]
      end
      skills_based_evaluation_criteria[level.id][:computational_thinking_skills].each do |criterion|
        evaluation_criteria << criterion[:evaluation_criteria]
      end
      evaluation_criteria
    elsif level.upper_grades_programming_level?
      return "Does the code run without errors? Does the code follow best practices?"
    else
      return level.properties["long_instructions"]
    end
  end
end
